### ISSUE TITLE
Expose the property isSdkReady to determine client is ready or not

### ISSUE THREAD

**Issue by sourabhguptavc** [splitio/ios-client#132]
Expose the property isSdkReady to determine client is ready or not. Because callback is not executed if following `on` is executed multiple times.

```
func on(event: SplitEvent, execute action: @escaping SplitAction)
```

**Comment by NicoZelaya** [comment]
Hi @sourabhguptavc ! 

Thank you very much for sharing, we'll submit a feature request on our end to track that. 

Regarding the callback not working, are you calling the on function and attaching the callback before the event is emitted? Or after? 
Do you see anything on the logs if you enable debug? You can see how to turn on the debug mode at the end of this table: https://help.split.io/hc/en-us/articles/360020401491-iOS-SDK#configuration

**Comment by sourabhguptavc** [comment]
@NicoZelaya I am getting the following warning

> "A handler was added for SDK_READY on the SDK, which has already fired and won’t be emitted again. The callback won’t be executed."

This warning is coming from the source code

```
// MARK: Events
extension DefaultSplitClient {
    public func on(event: SplitEvent, execute action: @escaping SplitAction) {
        if eventsManager.eventAlreadyTriggered(event: event) {
            Logger.w("A handler was added for \(event.toString()) on the SDK, " +
                "which has already fired and won’t be emitted again. The callback won’t be executed.")
            return
        }
        let task = SplitEventActionTask(action: action)
        eventsManager.register(event: event, task: task)
    }
}
```

**Comment by sourabhguptavc** [comment]
I think if event is already fired, then it should call `action` block

**Comment by NicoZelaya** [comment]
@sourabhguptavc got you. We basically use an event emitter approach and auto-executing the callback would go against that practice. That warning is the way we have to tell you that your callback won't be executed since the event was already fired. 
Nevertheless, what you want it's something we've discuss internally a few times because we understand that it can be confusing every now and then.

If you don't mind, before submitting it to have an internal discussion, I would like to understand more what's your use case.

- In which scenario you need to check for readiness at that point? 
- Are there multiple paths to that code and sometimes it might not be ready, but some other it will? 
- Would that be something you can achieve if we expose the status of the SDK with a function? 

Thank you for your feedback! 
Nico.

**Comment by sourabhguptavc** [comment]
> @sourabhguptavc got you. We basically use an event emitter approach and auto-executing the callback would go against that practice. That warning is the way we have to tell you that your callback won't be executed since the event was already fired.
> Nevertheless, what you want it's something we've discuss internally a few times because we understand that it can be confusing every now and then.
> 
> If you don't mind, before submitting it to have an internal discussion, I would like to understand more what's your use case.
> 
> * In which scenario you need to check for readiness at that point?
> * Are there multiple paths to that code and sometimes it might not be ready, but some other it will?
> * Would that be something you can achieve if we expose the status of the SDK with a function?
> 
> Thank you in advance for your feedback!
> Nico.

I will check the readiness all the time before calling `getTreatment` method.
I will create a Split client as a singleton, all the time when any code executing `getTreatment` will use this singleton instance of Split.
I think it should be ok if it is exposed with a function

**Comment by sourabhguptavc** [comment]
@NicoZelaya Is there any update on this

**Comment by nsillik** [comment]
I have a really similar architecture to @sourabhguptavc, I agree it'd be nice to either have the `on(event:)` called synchronously if the client is already ready or if an `sdkReady` property or method were exposed on the `SplitClient`

**Comment by NicoZelaya** [comment]
Hi! My apologies for our unresponsiveness. 

Yes, we have a feature currently in our backlog to expose the SDK status. We want to go just a bit further and have a function that exposes one of three statuses so you can know when the SDK is still syncing, when it's ready and when it's destroyed.

The reason why we would prefer not to work on the boolean method/property is because, as you may imagine, once we want to take that out and keep the other function to be consistent with the rest of the SDKs, it'll be a major change.

Is this a blocker for you guys? We could probably help you get around it with, for example, a wrapper. 
But if it's still a blocker and we can't figure it out without modifying the SDK, we can talk about temporarily exposing that function/property. We definitely wouldn't want to block your integration.

Best regards,
Nico.

**Comment by sourabhguptavc** [comment]
@NicoZelaya Is this fixed?
