### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by rpanichkin** [splitio/ios-client#247]
Hey guys.

I have the Split iOS SDK integrated into the project and use about 5 Splits.
After some time using the app, I see many Split-related objects in the memory (please see attached screenshots). Looks like a memory leak.

`destroy()` doesn't help and seems to do nothing.

Split SDK version: 2.11.0

<img width="1360" alt="Screenshot 2021-05-05 at 22 17 22" src="https://user-images.githubusercontent.com/19681073/119107232-dc33fd00-ba40-11eb-8e9e-26e20fb930ee.png">

<img width="1540" alt="Screenshot 2021-05-21 at 14 00 19" src="https://user-images.githubusercontent.com/19681073/119106451-308aad00-ba40-11eb-8313-f90413fe50d3.png">

**Comment by chillaq** [comment]
Hi @rpanichkin , thanks for the details, the SDK factory usually stays active with  background threads synching with Split cloud even if you don't use the client object.
Using client.destroy will stop these background threads, not sure if it will release all the SDK variables from memory though, will check with the team and let you know.

Thanks
Bilal

**Comment by rpanichkin** [comment]
Thanks! Looking forward

**Comment by chillaq** [comment]
Hi @rpanichkin ,  I have an answer from the team, this is by design,  when destroy() is called, all services stop but the memory is released when the reference to the SDK is released

So, if you  keeps a reference (factory and client objects), the SDK components will appear in the memory graph

Please let us know if you have any questions.

Thanks
Bilal
