### ISSUE TITLE
Treatment value takes time to reflect changes when treatment is fetched from SplitClient

### ISSUE THREAD

**Issue by jbatra-umeey** [splitio/ios-client#395]
I have a requirement wherein, I am supposed to update the menu items based on treatment flags from Dashboard. 

To speed up this, I am creating a new instance of `SplitClient` in order to read the changes quickly instead of waiting for the time delay as configured in polling mechanism

```
// Your Split API-KEY - Change in Config.swift file
let authorizationKey: String = "XXX"

//Provided keys from UI
let matchingKeyText: String = (matchingKey?.text)!
var bucketing: String? = nil

if let key = bucketkey?.text, !key.isEmpty() {
    bucketing = key
}

//Endpoints
let endpoints: ServiceEndpoints = ServiceEndpoints.builder()
    .set(sdkEndpoint: "xxx")
    .set(eventsEndpoint: "xxx")
    .set(authServiceEndpoint: "xxx")
    .set(streamingServiceEndpoint:"xxx")
    .build()


let config = SplitClientConfig()
config.serviceEndpoints = endpoints

//Split Configuration
config.featuresRefreshRate = 30
config.segmentsRefreshRate = 30
config.impressionRefreshRate = 30
config.sdkReadyTimeOut = 15000
config.connectionTimeout = 50
config.streamingEnabled = false

//User Key
let key: Key = Key(matchingKey: matchingKeyText, bucketingKey: bucketing)

//Split Factory
let builder = DefaultSplitFactoryBuilder()
self.factory = builder.setApiKey(authorizationKey).setKey(key).setConfig(config).build()

//Split Client
self.client = self.factory?.client

//Showing sdk version in UI
self.sdkVersion?.text = "SDK Version: \(self.factory?.version ?? "unknown") "

guard let client = self.client else {
    throw NSError(domain: "my error domain", code: 42, userInfo: ["ui1":12, "ui2":"val2"] )
    return
}


client.on(event: SplitEvent.sdkReady) {
    [unowned self, unowned client = client] in
    print("output----",output)
    client.destroy()


}

client.on(event: SplitEvent.sdkReadyTimedOut) {
    [unowned self] in
    client.destroy()
}

```

I have observed that even with this approach, the updates doesn't reflect instantly. It is intermittently slow and not consistent. 

In addition, I have disabled  streamingEnabled since it falls back to polling as per the documentation

`Boolean flag to enable the streaming service as default synchronization mechanism when in foreground. In the event of an issue with streaming, the SDK will fallback to the polling mechanism. If false, the SDK will poll for changes as usual without attempting to use streaming`

Am I missing anything or this behaviour is expected ?
Is there any other way to get quick updates from Dashboard ?

**Comment by agustinona** [comment]
Hi @jbatra-umeey,

I'd first point out that initializing a new factory in order to force a synchronization with Split is not a pattern we would recommend. By making use of our streaming architecture, a running SDK would get notified of any changes made to your splits through the web console and fetch them, typically resulting in sub-second latencies. Then, after the changes have been fetched, the SDK will fire its **sdkUpdated** event (see: https://help.split.io/hc/en-us/articles/360020401491-iOS-SDK#subscribe-to-events) which you can leverage to update your menu items.

That being said, I see two things here:
1) It seems you are setting custom endpoints for the SDK factory. Are you routing traffic through a proxy in your infrastructure? If so, that may be preventing the SSE connection that our streaming architecture depends on from established.
2) I don't see `getTreatment` being called in the code you shared, so I'm not sure how it is that you are consuming the treatments to update your menu items. Could you describe how it is that your are doing this?

**Comment by jbatra-umeey** [comment]
@agustinona thanks for your valuable response. I will go through the link you shared. 
Also, can you please let us know the scenarios in streaming can fail ?

For fetching treatment, I am using the below code to fetch latest flag values

```
client.on(event: SplitEvent.sdkReady) {
    [unowned self, unowned client = client] in
    let treatments = client.getTreatments(splits:splits, attributes: attributes)
    client.destroy()
}
```

**Comment by agustinona** [comment]
@jbatra-umeey improperly configured intermediaries such as proxies could prevent the SDK from reaching auth.split.io or streaming.split.io, which are required to establish the streaming connection. In rare cases, adblockers could block the connection as well. Any intermediaries (proxies, gateways) would need to be properly configured to allow the Server Side Events connection to streaming.split.io through as well.

None of this should be a concern if you use the default endpoints in the SDK config. Is your app connecting to Split through any intermediaries? Or are you seeing evidence of the streaming connection failing? If so, could you provide the SDK debug logs so that we may look into it?

> For fetching treatment, I am using the below code to fetch latest flag values
> 
> client.on(event: SplitEvent.sdkReady) {
>     [unowned self, unowned client = client] in
>     let treatments = client.getTreatments(splits:splits, attributes: attributes)
>     client.destroy()
> }

If you want to recalculate treatments as soon as the SDK receives an update, you should use the sdkUpdated event as well. sdkReady will fire only once during the SDK lifecycle after initialization, but sdkUpdated may fire many times as soon as the already running SDK fetches an update from the Split Cloud. In this way you can reactively update your UI without the need to reinstantiate the SDK factory.

**Comment by agustinona** [comment]
Hi @jbatra-umeey I'm following up on this. Are you still having issues getting updated treatments?

**Comment by jbatra-umeey** [comment]
@agustinona , as of now we are initialising a new client  as mentioned in https://github.com/splitio/ios-client/issues/395#issue-1434205263 and fetching the updated values like below :  

```
client.on(event: SplitEvent.sdkReady) {
[unowned self, unowned client = client] in
let treatments = client.getTreatments(splits:splits, attributes: attributes)
client.destroy()
}
```

We plan to implement the streaming architecture in phase 2. I shall be able to to let you know the progress and performance once we have it ready. Meanwhile, do you have any samples/tips for the best practices ?

**Comment by agustinona** [comment]
Hi @jbatra-umeey,

I apologize for the late response. The main best practice is to instantiate and use a single factory throughout your app. Instantiating new factories to fetch updated treatments is not efficient. By having streaming enabled, your SDK would receive any changes made to your splits almost instantly (typically under a second) and fire the **sdkUpdated** event to let you know new definitions have been cached and are available for evaluation.

May I ask why is enabling streaming being delegated to phase 2? Is there any blocker currently for enabling streaming and using the appropriate event to update your treatments? I believe creating multiple factory instances now will mean unnecessary extra work for you going forward once you enable streaming and move onto a proper singleton pattern.

Best,
Agus

**Comment by agustinona** [comment]
@jbatra-umeey ping :)

**Comment by agustinona** [comment]
@jbatra-umeey We haven't heard back from you in a while, so I'm closing this issue. If you still require assistance please feel free to reopen.
