### ISSUE TITLE
Git repository is very large for SPM

### ISSUE THREAD

**Issue by SajjadKharrazi** [splitio/ios-client#450]
When we want to download or update you package with SPM, it takes too long as you can see:

<img width="431" alt="image" src="https://github.com/splitio/ios-client/assets/7239983/3b4890c5-beca-4e3a-9927-e6c04d3d8d87">

I'm not sure but i think your package size is about 30MB and it is large for this SDK

I think you should have an approach like these SDKs to reduce downloading time
https://github.com/airbnb/lottie-ios/discussions/1807
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1053

**Comment by hbqdev** [comment]
hi @SajjadKharrazi 
We are checking this with our dev team and will get back to you.

Regards,

**Comment by hbqdev** [comment]
hi @SajjadKharrazi 
We are sorry for this inconvenience. We understand your concern and after some digging we found testing resources files to be the largest contributors to the SPM download size. To our understanding, this is only affecting the time taking to download the package but there is no impact on app bundle size since is not included there. We are taking this as RFE to evaluate approaches to keep a reduced SDK size without affecting testing coverage.

Regards
